aircraft/urls.py
from django.conf.urls.defaults import *
from django.views.generic import create_update
#from forms import AircraftForm

urlpatterns = patterns('aircraft',
        url(
                r'^$',
                "views.make_list",
                name="list-aircraft"
        ),
        
        url(
                r'^(?P<pk>\d*)-(?P<slug>[a-z0-9\-]*)\.html$',
                "views.view",
                name="view-aircraft"
        ),
        
        url(
                r'^new/$',
                "views.new",
                name="new-aircraft"
        ),
        
        url(
                r'^edit/(?P<pk>\d{1,4})/$',
                "views.edit",
                name="edit-aircraft"
        ),
)

airport/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('airport',

        url(
            r'^(?P<ident>\S{1,7}).html$',
            "views.airport",
                                                           name="view-airport",
        ),
        
        url(
            r'^(?P<ident>[A-Z0-9]{1,7}).kmz$',
            "views.kmz",
                                                            name="kml-airport",
        ),
)

position/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('position',
    url(
        r'^$',
        "views.make_list",
                                                          name="list-position",
    ),
    
    url(
        r'^(?P<pk>\d{1,4})\.html$',
        "views.view",
                                                          name="view-position",
    ),
    
    url(
        r'^new/(?P<pk>\d{1,4})/$',
        "views.new",
                                                           name="new-position",
    ),
    
    url(
        r'^edit/(?P<pk>\d{1,4})/$',
        "views.edit",
                                                          name="edit-position",
    ),
    
    url(
        r'^(?P<pk>\d*)\.kmz$',
        "views.kml",
                                                          name="kml-position",
    ),
)

urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to, direct_to_template

################################################

from django.contrib import admin

admin.autodiscover()

#################################################

from sitemaps import *

sitemaps = {"company": CompanySitemap,
            "aircraft": AircraftSitemap,
            "position": PositionSitemap,
            "airport": AirportSitemap,
           }

#################################################

urlpatterns = patterns('',

    (r'^overlay/(?P<z>\d{1,2})_(?P<x>\d{1,5})_(?P<y>\d{1,5})_(?P<o>\S{1,5}).png$',
                                'jobmap.views.overlay'),
                            
    (r'^map_click/(?P<z>\d{1,2})_(?P<lat>\-?\d+\.\d*)_(?P<lng>\-?\d+\.\d*)/$',
                                'jobmap.views.click'),

    ###########################################################################

    url('^$',                   redirect_to, {'url': 'about.html'}),

    (r'^admin/',                include(admin.site.urls)),
    (r'^admin/doc/',            include('django.contrib.admindocs.urls')),
    (r'^comments/',             include('mod_comments.urls')),
    
    (r'^robots.txt$',           include('robots.urls')),
    
    ###########################################################################

    (r'^airport/',              include("airport.urls")),
    (r'^aircraft/',             include("aircraft.urls")),
    (r'^route/',                include("route.urls")),

    (r'^mins/',                 include("mins.urls")),
    (r'^company/',              include("company.urls")),
    (r'^position/',             include("position.urls")),
    (r'^fleet/',                include("fleet.urls")),
    (r'^operation/',            include("operation.urls")),

    url(r'^latest\.html$',      "main.views.latest", name="latest"),
    url(r'^about\.html$',       "main.views.about", name="about" ),
    url(r'^jobmap\.html',       "jobmap.views.jobmap", name="jobmap"),
    url(r'^profile\.html',      "profile.views.profile", name="profile"),

    (r'^openid/',               include('django_openid_auth.urls')),

    (r'fl-uploads/.+\.txt',     "main.views.remove_uploads", ),
    
###############################################################################

#    url(
#        r'^kmz/position-(?P<position>\d+).kmz$',
#        "jobmap.views.kml",
#                                                           name="position-kml",
#    ),
    
#    url(
#        r'^kmz/company-(?P<company>\d+).kmz$',
#        "jobmap.views.kml",
#                                                            name="company-kml",
#    ),
        
#    url(
#        r'^kmz/airport-(?P<airport>\S+).kmz$',
#        "jobmap.views.kml",
#                                                            name="airport-kml",
#    ),

    (
        r'^dev-media/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': '/srv/fanmarkers/media', 'show_indexes': True}
    ),
    
    (
        r'^sitemap.xml$',
        'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': sitemaps}
    ),

)

urlpatterns += patterns('django.contrib.auth',
    url(
        r'^accounts/logout/$','views.logout',
        {"template_name": "about.html"},                        name="logout"),
)

aircraft/models.py
from django.db import models
from django.db.models import permalink
from django.contrib.auth.models import User
from constants import *

from django.template.defaultfilters import slugify

class Aircraft(models.Model):
    manufacturer    =       models.CharField(max_length=32, help_text="e.g: Cessna, Beechcraft")
    type            =       models.CharField(max_length=32, help_text="e.g: C-172, BE-76")
    model           =       models.CharField(max_length=64, help_text="e.g: Skyhawk, Duchess", blank=True)
    extra           =       models.CharField(max_length=32, help_text="e.g: RG, on floats", blank=True)
    engine_type     =       models.IntegerField("Engine Type", choices=ENGINE_TYPE, default=0)
    cat_class       =       models.IntegerField("Category/Class", choices=CAT_CLASSES, default=1)
    watchers        =       models.ManyToManyField(User, blank=True, )

    class Meta:
        ordering = ["manufacturer", "type"]

    @permalink
    def get_absolute_url(self):
        return ('view-aircraft', [str(self.pk), self.slug] )

    @permalink
    def get_edit_url(self):
        return ('edit-aircraft', [str(self.pk)] )

    def slugify(self):
        if self.extra:
            model = " " + self.model + " " + self.extra
        elif self.model:
            model = " " + self.model
        else:
            model = ""
        return slugify(u'%s %s' % (self.manufacturer, model) )

    slug = property(slugify)

    def __unicode__(self):
        if self.model and self.type:
            return u"%s %s %s (%s)" % (self.manufacturer, self.model, self.extra, self.type)

        elif self.model and not self.type:
            return u"%s %s %s" % (self.manufacturer, self.model, self.extra)

        elif self.type and not self.model:
            return u"%s %s %s" % (self.manufacturer, self.type, self.extra)

route/models.py
from django.db import models
from django.db.models import permalink
from airport.models import Airport
from operation.models import OpBase

class Route(models.Model):
    bases           = models.ManyToManyField(Airport, through="RouteBase", blank=True)
    description     = models.TextField(blank=True)
    home            = models.ForeignKey(OpBase, blank=True)

    @permalink
    def get_edit_url(self):
        return ('edit-route', str(self.pk) )

    def __unicode__(self):
        ret = []
        for rb in self.real_route():
            ret.append(rb.base.identifier)

        return "-".join(ret)

    def real_route(self):

        base = RouteBase(base=self.home.base)           #create a routebase of the home base, so the output is all routebases

        points = RouteBase.objects.filter(route__pk=self.pk)

        return [base] + list(points) + [base]


###############################################################################################################################

class RouteBase(models.Model):
    base            = models.ForeignKey(Airport)
    route           = models.ForeignKey("Route")
    sequence        = models.IntegerField(blank=True)

    class Meta:
        ordering = ['sequence']

    def __unicode__(self):
        return u"%s" % (self.base,)

aircraft/forms.py
from django import forms
from django.forms import ModelForm

from models import Aircraft
from constants import ENGINE_TYPE, CAT_CLASSES

class AircraftForm(ModelForm):
    class Meta:
        model = Aircraft
        exclude = ('watchers', )

class AircraftSearch(forms.Form):
    search          =       forms.CharField(max_length=100, required=False)
    engine_type     =       forms.ChoiceField(choices=[(-1,"Any",),]+ENGINE_TYPE, label="Engine Type", required=False)
    cat_class       =       forms.ChoiceField(choices=[(-1,"Any",),]+CAT_CLASSES, label="Category/Class", required=False)

position/forms.py
from django.forms import ModelMultipleChoiceField, HiddenInput, ModelForm

from models import *
from airport.models import Airport

class StatusForm(ModelForm):
    not_bases =    ModelMultipleChoiceField(
                            queryset=Airport.objects.all(),
                            widget=HiddenInput,
                            required=False)
                            
    choice_bases = ModelMultipleChoiceField(
                            queryset=Airport.objects.all(),
                            widget=HiddenInput,
                            required=False)
                            
    assign_bases = ModelMultipleChoiceField(
                            queryset=Airport.objects.all(),
                            widget=HiddenInput,
                            required=False)
                           
    layoff_bases = ModelMultipleChoiceField(
                            queryset=Airport.objects.all(),
                            widget=HiddenInput,
                            required=False)

    class Meta:
        model = Status

class PositionForm(ModelForm):
    class Meta:
        model = Position
        exclude = ('watchers', 'mins', 'company')

aircraft/views.py
from django.contrib.auth.decorators import login_required
from annoying.decorators import render_to
from django.shortcuts import get_object_or_404
from django.views.generic.create_update import update_object, create_object
from django.db.models import Q

from django.http import HttpResponseRedirect


from company.models import Company
from forms import AircraftForm, AircraftSearch
from models import Aircraft

################################

@render_to('view_aircraft.html')
def view(request, pk, slug):
    aircraft = get_object_or_404(Aircraft, pk=pk)

    if not aircraft.slug == slug:
        return HttpResponseRedirect(aircraft.get_absolute_url() )

    companies = Company.objects.filter(fleet__aircraft=aircraft)
    return locals()

@login_required()
def edit(request, pk):
    return update_object(request,
                         object_id=pk,
                         form_class=AircraftForm,
                         template_name="new-edit_aircraft.html")

@login_required()
def new(request):
    return create_object(request,
                         form_class=AircraftForm,
                         template_name="new-edit_aircraft.html")

@render_to('list_aircraft-company.html')
def make_list(request):
    objects = Aircraft.objects.all()
    type="Aircraft"
    if request.GET.get("cat_class", False):
        searchform = AircraftSearch(request.GET)
        searchform.is_valid()

        if int(searchform.cleaned_data["cat_class"]) >= 0:
            objects = objects.filter(cat_class=searchform.cleaned_data["cat_class"])

        if int(searchform.cleaned_data["engine_type"]) >= 0:
            objects = objects.filter(engine_type=searchform.cleaned_data["engine_type"])

        if searchform.cleaned_data["search"]:
            s = searchform.cleaned_data["search"]
            objects = objects.filter( Q(manufacturer__icontains=s) | Q(type__icontains=s) | Q(model__icontains=s) | Q(extra__icontains=s) )

    else:
        searchform = AircraftSearch()
    return locals()

airport/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404

from annoying.decorators import render_to

from models import *
from company.models import Company
from operation.models import Operation

################################

@render_to('view_airport.html')
def airport(request, ident):

    airport = get_object_or_404(Airport, identifier=ident)

    #ops where this airport is a base
    company_base =  Company.objects\
                           .filter(operation__opbase__base=airport)\
                           .distinct()
    
    #ops where this airport is part of a route                    
    ops_fly =       Operation.objects\
                             .filter(opbase__route__bases=airport)\
                             .distinct()

    kmz_url = reverse("kml-airport", kwargs={"ident": ident})

    return locals()

def kmz(request, ident):

    base = Airport.goof(identifier=ident)
    
    title = "%s - %s" % (ident, base.name)
    #make it a list so it can be iterated in the template
    bases = (base, )
    
    from kml.utils import locals_to_kmz_response
    return locals_to_kmz_response(locals())

templates/view/aircraft.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block css %}
	<style type="text/css">
		.operations_box			{border: 1px solid black; background: lightgray; padding: 5px}
	</style>
{% endblock %}

{% block javascript %}

{% endblock %}

{% block body %}
<div id="main_container">

	<h1>{{aircraft}}</h1>
	
	<hr class="top_divider" />
	
	<table summary="aircraft specs">
		<tr>
			<td>Type:</td>
			<td>{{aircraft.type}}</td>
		</tr>
		
		<tr>
			<td>Model:</td>
			<td>{{aircraft.model}}</td>
		</tr>
		
		<tr>
			<td>Manufacturer:</td>
			<td>{{aircraft.manufacturer}}</td>
		</tr>
		
		<tr>
			<td>Category/Class:</td>
			<td>{{aircraft.get_cat_class_display}}</td>
		</tr>
		
		<tr>
			<td>Engine Type:</td>
			<td>{{aircraft.get_engine_type_display}}</td>
		</tr>
	</table>
	
	<hr />
	
	<div class="operations_box">
	<h3>Operations that use this aircraft:</h3>
	{% if operations %}
	<ul>
	{% for op in operations %}
	<li>
	<a href="/company/{{op.company.pk}}/#op{{op.pk}}">{{op}}</a>
	</li>
	{% endfor %}
	</ul>
	{% else %}
	
	<em>None</em>
	
	{% endif%}
	</div>

</div>
{% endblock %}

templates/view/airport.html
{% extends "base.html" %}

{% block title %}{{ a.identifier }} - Airport Profile{% endblock %}

{% block css %}
	<style type="text/css">
		.airport_positions		{background: #DDDDDD; border: 1px solid black; padding: 1em; margin-bottom: 1em}
	</style>
{% endblock %}

{% block javascript %}

	<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key={{ GOOGLE_MAPS_KEY }}" type="text/javascript"></script>
	
	<script type="text/javascript">
		airport_lat = {{a.location.y}};
		airport_long = {{ a.location.x}};
		
		var icon = new GIcon;
		icon.image = '{{ MEDIA_URL }}/icons/big/red.png';
		icon.iconSize = new GSize(16,16);
		icon.iconAnchor = new GPoint(8,8);
		icon.infoWindowAnchor = new GPoint(16,16);

		var sicon = new GIcon;
		sicon.image = "{{ MEDIA_URL }}/icons/small/red.png";
		sicon.iconSize = new GSize(8,8);
		sicon.iconAnchor = new GPoint(4,4);
		sicon.infoWindowAnchor = new GPoint(8,8);
	</script>
	
	<script type="text/javascript" src="{{ MEDIA_URL }}/javascripts/small_map.js"></script>
	
	<script type="text/javascript">
		window.onunload = GUnload;
		window.onload = initialize_airport;
	</script>

{% endblock %}

{% block body %}
<div id="main_container">
	{% if not_found %}
		<h1>Airport Not Found</h1>
	{% else %}


		<h1>{{ a.identifier }} - {{ a.name }}</h1>
		<div>{%if a.municipality%}{{a.municipality}}, {%endif%}{{a.region}}, {{a.country}}</div>
	
		<div id="small_map" class="small_map"></div>
	
		<div class="airport_positions">
			<big>Operations based at this airport:</big>
			<br /><br />

			{% for op in ops_base %}
				<a href="/company/{{ op.company.pk }}#op{{ op.pk }}">{{ op.company }} - {{ op.all_fleet }}</a><br />
			{% endfor %}
		
			{% if not ops_base %}
				<em>None</em>
			{% endif %}
		</div>
	
		<div class="airport_positions">
			<big>Operations that fly to this airport:</big>
			<br /><br />

			{% for op in ops_fly %}
				<a href="/company/{{ op.company.pk }}#op{{ op.pk }}">{{ op.company }} - {{ op.all_fleet }}</a><br />
			{% endfor %}
		
			{% if not ops_fly %}
				<em>None</em>
			{% endif %}
		</div>
	
	{% endif %}
</div>
{% endblock %}

templates/view/jobmap.html
{% extends "base.html" %}

{% block title %}Jobmap{% endblock %}

{% block css %}
		<style type="text/css">
			#container				{height: 100%; overflow: hidden}
			#map_canvas				{height: 100%; width: 100%; float: left; background: green;    border: 0px solid black}
			#sidebar				{height: 100%; width: 100%; float: left; background: #FFDDFF;  border: 0px solid black; padding-top: 20px}
		
			#container table			{height: 100%; width: 100%; border-collapse: collapse}
			#container table tr			{height: 100%}
			td					{height: 100%}
			#container table td:last-child		{width: 20em; height: 100%}
		
			#submit_sidebar				{margin-left: auto; margin-right: auto}
		</style>
{% endblock %}

{% block javascript %}

	

	<script src="http://maps.google.com/maps?file=api&amp;v=2.x&amp;key={{ GOOGLE_MAPS_KEY }}" type="text/javascript">
	</script>
	
	<script type="text/javascript">
		var map;		//map is in global scope
		var domain = "{{ domain }}";
		
		var CustomGetTileUrl = function(point,zoom){
		
			if ( zoom == 9 )	// Only retrieve a tile from the script on zoom level 9
				return "overlay_" + zoom + "_" + point.x + "_" + point.y + "_" + sessionKey;
			else
				return "overlay_0_0_0" ;	// Otherwise, use a blank image
		}

		
		var DestOverlay = new GTileLayerOverlay(
			new GTileLayer(null, null, null, {
				tileUrlTemplate: 'http://' + domain + '/overlay_{Z}_{X}_{Y}_DMB/', 
				isPng:true,
				opacity:1.0
				}
			)
		);
		
		var BaseOverlay = new GTileLayerOverlay(
			new GTileLayer(null, null, null, {
				tileUrlTemplate: 'http://' + domain + '/overlay_{Z}_{X}_{Y}_BMB/', 
				isPng:true,
				opacity:1.0
					}
			)
		);
		
		africa = new GGeoXml('http://other.flightlogg.in/kml/africa.kmz');
		americas = new GGeoXml('http://other.flightlogg.in/kml/americas.kmz');
		carribean = new GGeoXml('http://other.flightlogg.in/kml/carribean.kmz');
		alaska = new GGeoXml('http://other.flightlogg.in/kml/alaska.kmz');
		austrailia = new GGeoXml('http://other.flightlogg.in/kml/austrailia.kmz');
		canada = new GGeoXml('http://other.flightlogg.in/kml/canada.kmz');
		china = new GGeoXml('http://other.flightlogg.in/kml/china.kmz');
		eastern_europe = new GGeoXml('http://other.flightlogg.in/kml/eastern_europe.kmz');
		europe = new GGeoXml('http://other.flightlogg.in/kml/europe.kmz');
		india = new GGeoXml('http://other.flightlogg.in/kml/india.kmz');
		indonesia = new GGeoXml('http://other.flightlogg.in/kml/indonesia.kmz');
		middle_east = new GGeoXml('http://other.flightlogg.in/kml/middle_east.kmz');
		russia = new GGeoXml('http://other.flightlogg.in/kml/russia.kmz');
		scandanavia = new GGeoXml('http://other.flightlogg.in/kml/scandanavia.kmz');
		usa = new GGeoXml('http://other.flightlogg.in/kml/usa.kmz');
		
	</script>
	
	<script type="text/javascript" src="{{ MEDIA_URL }}/javascripts/big_map.js">
	</script>
	
{% endblock %}

{% block body %}	
	<div id="container">
		<table>
			<tr>
				<td><div id="map_canvas"></div></td>
				<td>
					<form action="." method="get">
					<div id="sidebar">
					Show:<br />	<input type="checkbox" id="c_bases" />Job bases<br />
							<input type="checkbox" id="c_destinations" />Destination airports<br />
							
					<hr />
							
					Filter:		<select id="d_filter">
								<option>Show All</option>
								<option>Only Advertising</option>
								<option>Only Hiring</option>
								<option>Only Lay-off</option>
								<option>Only no-status</option>
							</select>
														
							<br />
							
					<hr />
							
					By Aircraft:	<select id="d_aircraft">
								<option>All</option>
							</select>
							
							<br />
							
					By Schedule:	<select id="d_schedule">
								<option>All</option>
								<option>On Call</option>
								<option>Scheduled</option>
							</select>
							
							<br />
							
					<hr />
							
					Only show jobs I'm qualified for: <input type="checkbox" /><br />
							
							<br />
					
					Search: <input type="text" /><br />
					
					<br />
					
					<input id="submit_sidebar" type="submit" value="Go" />
				
					</div>
					</form>
				</td>
			</tr>
		</table>
	</div>
	
{% endblock %}

templates/view/position.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}{% endblock %}

{% block css %}
	<style type="text/css">
	.base			{border: 1px solid black; margin-top: 1em; padding: 0.5em; overflow: hidden}
	.base_link		{font-weight: bold}
	.base_info		{display: none}
	.base_floats		{float: left; padding-right: 1em}
	
	.plus			{cursor: pointer}
	
	.routes_table		{border-collapse: collapse; margin-top: 1em}
	.routes_table td	{padding-right: 2em}

	.position_box		{border: 1px solid black; margin-bottom: .5em; padding: .5em; font-size: medium}
	.position_status	{font-size: medium}
	.position_name		{font-size: x-large; font-weight: bold}
	.payscale		{border-collapse: collapse; font-size: medium; margin-top: 1em}
	.payscale td		{border: 1px solid gray;  padding: 3px}
	
	.position_mins		{margin-top: 1em; border-collapse: collapse}
	.position_mins td	{border: 0px solid black; padding-right: 1em}
	
	.info_table		{border: 1px solid black; padding: 1em}
	.info_table td:first-child	{width: 8em}
	
	ul			{margin-top: 0}
	
	</style>
{% endblock %}

{% block javascript %}

<script src="http://maps.google.com/maps?file=api&amp;v=2.x&amp;key={{ GOOGLE_MAPS_KEY }}" type="text/javascript"></script>

<script type="text/javascript">
	var icon = new GIcon;
	icon.image = '{{ MEDIA_URL }}/icons/big/red.png';
	icon.iconSize = new GSize(16,16);
	icon.iconAnchor = new GPoint(8,8);
	icon.infoWindowAnchor = new GPoint(16,16);

	var sicon = new GIcon;
	sicon.image = "{{ MEDIA_URL }}/icons/small/red.png";
	sicon.iconSize = new GSize(8,8);
	sicon.iconAnchor = new GPoint(4,4);
	sicon.infoWindowAnchor = new GPoint(8,8);
</script>

<script type="text/javascript" src="{{ MEDIA_URL }}/javascripts/small_map.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}/javascripts/position_doc_ready.js"></script>

<script type="text/javascript">
	var bases = [];	//lat longs of all bases, indexed by the pk of that opbase
	var maps = [];	//array of the Gmap2 objects
	var data = [];	//array of all the points, indexed by the opbase pk
	
{% for ob in p.opbases %}
	bases[{{ob.pk}}] = [{{ob.base.location.y}},{{ob.base.location.x}}]; 
	data[{{ob.pk}}] = {% if ob.routes.all %}{{ob.routes_json}}{%else%}"None";{% endif %}
{% endfor %}
</script>

{% endblock %}

{% block body %}
<div id="main_container">


	<h2>
		<a href="{{p.company.get_absolute_url}}">{{p.company.name}}</a>
		>
		<a href="/edit{{p.company.get_absolute_url}}" class="edit_link">
			<img src="{{ MEDIA_URL }}/icons/edit.png" alt="Click to edit" />
		</a>
		
		{{p.name}}
	</h2>
	
	<hr class="top_divider" />
	
	<table class="info_table" summary="payscale and hiring minimums information">
	
	{% if p.payscaleyear_set.all %}
		<tr>
			<td>Salary:</td>
			<td>
			<strong>
				{% for ps in p.payscaleyear_set.all %}
				{% if forloop.last and forloop.first %}
					${{ ps.amount|floatformat:2|intcomma }} <small>{{ ps.get_salary_unit_display }}</small>		
				{% else %}
					{{ ps.year|ordinal }} year: ${{ ps.amount|floatformat:2|intcomma }} <small>{{ ps.get_salary_unit_display }}</small><br />
				{% endif %}
				{% endfor %}
			</strong>
			</td>
		</tr>
		
	{% else %}
		<tr><td><em>No known salary information</em></td></tr>
	{% endif %}

		<tr>
			<td colspan="2"><hr /></td>
		</tr>
		
		{% if p.hard_mins.has %}
		<tr>
			<td>Hard Minimums:</td>
			<td>{{p.hard_mins.as_ul|safe}}</td>
		</tr>
		{% endif %}

		{% if p.pref_mins.has %}
		<tr>
			<td>&nbsp;</td>
		</tr>
		
		<tr>
			<td>Preferred:</td>
			<td>
				{% for r in p.pref_mins.display_pref %}
				{{r|join:" "}}<br />
				{% endfor %}
			</td>
		</tr>
		{% endif %}
	
		{% if not p.pref_mins.has and not p.hard_mins.has %}
			<tr>
				<td colspan="2"><em>No known hiring minimums</em></td>
			</tr>
		{% endif %}
	</table>


{% for ob in p.opbases %}
	<div class="base b{{ ob.hiring_status }}">
		<div class="base_floats">
			<img title="Click to expand" class="plus" id="expand_{{ob.pk}}" src="{{ MEDIA_URL }}/icons/plus.png" alt="+"/>
		</div>
		<div class="base_floats">
			<a title="{{ ob.base.get_location }}" class="base_link" href="/airport/{{ ob.base.identifier }}">
				{{ ob.base.display_name }}</a> {{ ob.get_hiring_status_display }} ({{ob.workforce_size}})<br />
				<small>{{ ob.base.municipality }}, {{ ob.base.region }}{% ifnotequal ob.base.country "United States"%}, {{ ob.base.country }}{% endifnotequal %}</small>
			
			<div class="base_info" id="info_{{ob.pk}}" >
				<div id="map_{{ob.pk}}" class="small_map"></div>
			
			
				{% if ob.routes.all %}
					<table class="routes_table">
					{% for r in ob.routes.all %}		{# new row, new route #}
						<tr>
						{% if forloop.first %}
							<td>Routes:</td>
						{% else %}
							<td></td>
						{% endif %}
					
						<td>
						{{r.get_often_display}}
						<a href="/airport/{{ ob.base.identifier }}" title="{{ ob.base.city }}, {{ ob.base.sector }}">{{ ob.base.identifier }}</a> &#8594; 
						{% for b in r.routebase_set.all %}
						<a href="/airport/{{ b.base.identifier }}" title="{{ b.base.city }}, {{ b.base.sector }}">{{ b.base.identifier }}</a> &#8594; 
						{% if forloop.last%}
						<a href="/airport/{{ ob.base.identifier }}" title="{{ ob.base.city }}, {{ ob.base.sector }}">{{ ob.base.identifier }}</a>
						{% endif %}
						{% endfor%}
						</td>
						</tr>
					{% endfor %}
					</table>
				{% endif %}
			</div>
		</div>
	</div>
{% endfor %}
	
	
</div>
{% endblock %}