urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to, direct_to_template

################################################

from django.contrib import admin

admin.autodiscover()

#################################################

from sitemaps import *

sitemaps = {"company": CompanySitemap,
            "aircraft": AircraftSitemap,
            "position": PositionSitemap,
            "airport": AirportSitemap,
           }

#################################################

urlpatterns = patterns('',

    (r'^overlay/(?P<z>\d{1,2})_(?P<x>\d{1,5})_(?P<y>\d{1,5})_(?P<o>\S{1,5}).png$',
                                'jobmap.views.overlay'),
                            
    (r'^map_click/(?P<z>\d{1,2})_(?P<lat>\-?\d+\.\d*)_(?P<lng>\-?\d+\.\d*)/$',
                                'jobmap.views.click'),

    ###########################################################################

    url('^$',                   redirect_to, {'url': 'about.html'}),

    (r'^admin/',                include(admin.site.urls)),
    (r'^admin/doc/',            include('django.contrib.admindocs.urls')),
    (r'^comments/',             include('mod_comments.urls')),
    
    (r'^robots.txt$',           include('robots.urls')),
    
    ###########################################################################

    (r'^airport/',              include("airport.urls")),
    (r'^aircraft/',             include("aircraft.urls")),
    (r'^route/',                include("route.urls")),

    (r'^mins/',                 include("mins.urls")),
    (r'^company/',              include("company.urls")),
    (r'^position/',             include("position.urls")),
    (r'^fleet/',                include("fleet.urls")),
    (r'^operation/',            include("operation.urls")),

    url(r'^latest\.html$',      "main.views.latest", name="latest"),
    url(r'^about\.html$',       "main.views.about", name="about" ),
    url(r'^jobmap\.html',       "jobmap.views.jobmap", name="jobmap"),
    url(r'^profile\.html',      "profile.views.profile", name="profile"),

    (r'^openid/',               include('django_openid_auth.urls')),

    (r'fl-uploads/.+\.txt',     "main.views.remove_uploads", ),
    
###############################################################################

#    url(
#        r'^kmz/position-(?P<position>\d+).kmz$',
#        "jobmap.views.kml",
#                                                           name="position-kml",
#    ),
    
#    url(
#        r'^kmz/company-(?P<company>\d+).kmz$',
#        "jobmap.views.kml",
#                                                            name="company-kml",
#    ),
        
#    url(
#        r'^kmz/airport-(?P<airport>\S+).kmz$',
#        "jobmap.views.kml",
#                                                            name="airport-kml",
#    ),

    (
        r'^dev-media/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': '/srv/fanmarkers/media', 'show_indexes': True}
    ),
    
    (
        r'^sitemap.xml$',
        'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': sitemaps}
    ),

)

urlpatterns += patterns('django.contrib.auth',
    url(
        r'^accounts/logout/$','views.logout',
        {"template_name": "about.html"},                        name="logout"),
)

base/models.py
from django.contrib.gis.db import models
from django.contrib.auth.models import User
from main.constants import AIRPORT_TYPE
from django.db.models import Q

class BaseManager(models.GeoManager):
	def get_query_set(self):				#all airports which are an opbase
		return super(BaseManager, self).get_query_set().filter(opbase__isnull=False).distinct()
		
class HiringManager(BaseManager):
	def get_query_set(self):				#is a base, and either choice or assign are not null
		return super(BaseManager, self).get_query_set().filter( Q(opbase__assign__isnull=False) | Q(opbase__choice__isnull=False)).distinct()	
		
class NotHiringManager(BaseManager):
	def get_query_set(self):				#is a base, and both choice and assign are null
		return super(BaseManager, self).get_query_set().filter( Q(opbase__assign__isnull=True) & Q(opbase__choice__isnull=True)).distinct()	
		
class RouteManager(models.GeoManager):
	def get_query_set(self):				#is a routebase, but not an opbase
		return super(RouteManager, self).get_query_set().filter( Q(routebase__isnull=False) & Q(opbase__isnull=True) ).distinct()
		
class RelevantManager(models.GeoManager):
	def get_query_set(self):				#is an opbase, or a routebase
		return super(RelevantManager, self).get_query_set().filter( Q(routebase__isnull=False) | Q(opbase__isnull=False) ).distinct()

class Airport(models.Model):
	identifier	=	models.CharField(max_length=8, primary_key=True)
	
	name		=	models.CharField(max_length=96)
	municipality	=	models.CharField(max_length=60)
	country		=	models.ForeignKey("Country")
	region		=	models.ForeignKey("Region")
	type		=	models.IntegerField(choices=AIRPORT_TYPE)
	
	elevation	=	models.IntegerField(null=True)
	location	=	models.PointField()
	
	watchers	=	models.ManyToManyField(User, blank=True, )
	
	objects		=	models.GeoManager()
	hiring		=	HiringManager()
	base		=	BaseManager()
	not_hiring	=	NotHiringManager()
	route		=	RouteManager()
	relevant	=	RelevantManager()
	
	class Meta:
		ordering = ["identifier", "country"]
		verbose_name_plural = "Airports"
		
	def get_absolute_url(self):
		return "/airport/%s/" % (self.identifier, )
		
	def __unicode__(self):
		return u"%s - %s" % (self.identifier, self.location_summary())
		
	def display_name(self):
		return " - ".join([self.identifier, self.name])

	def location_summary(self):
		ret = []
		
		for item in (self.municipality, self.region.name, self.country.name, ):
			if item and item != "United States":
				ret.append(item)
				
		return ", ".join(ret)
		
class Region(models.Model):
	code = models.CharField(max_length=48)
	country = models.CharField(max_length=2)
	name = models.CharField(max_length=60)
	
	def __unicode__(self):
		return "%s" % (self.name)
	
class Country(models.Model):
	name = models.CharField(max_length=48)
	code = models.CharField(max_length=2, primary_key=True)
	
	def __unicode__(self):
		return self.name

profile/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user            =       models.ForeignKey(User, primary_key=True)
    dob             =       models.DateField("Date of Birth", blank=True, default="1900-01-01")
    #resume         =       models.FileField(upload_to="resume/")

profile/forms.py
from django.forms import ModelForm
from models import Profile
from django.contrib.auth.models import User

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ('user', )

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', )

profile/views.py
from annoying.decorators import render_to
from annoying.functions import get_object_or_None

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

from models import Profile

@login_required()
@render_to('profile.html')
def profile(request):
    from forms import ProfileForm, UserForm

    user = request.user
    profile = get_object_or_None(Profile, user=user)

    if not profile:
        profile = Profile(user=user)

    if request.method == "POST":
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
        user_form = UserForm(request.POST, instance=user)

        if profile_form.is_valid() and user_form.is_valid():
            profile_form.save()
            user_form.save()

            return HttpResponseRedirect( "/" )
    else:
        profile_form = ProfileForm(instance=profile)
        user_form = UserForm(instance=user)

    return locals()

templates/base_account.html
{% extends "base.html" %}
{% load humanize %}

{% block javascript %}{% endblock %}

{% block body %}
<div id="main_container">
	<h1>
	{% block heading %}{% endblock %}
	</h1>
	{% block sub_heading %}{% endblock %}
	
	<div class="last_modified" >{% if last_modified %}Last Modified: {{last_modified|date:"Y-M-d, T"}}{% endif %} &nbsp; </div>
	<hr/>
	
	{% block form %}{% endblock %}
</div>
{% endblock %}

templates/base_form.html
{% extends "base.html" %}
{% load humanize %}

{% block javascript %}{% endblock %}

{% block css %}
{{ block.super }}
/******************************************/
/*             base form                  */
/******************************************/
	.form_table td[colspan="2"]	{border:none; text-align: right; background: white !important; padding: 0px}
	
	.form_table			{width: 100%; border-collapse: collapse}
	.form_table th			{width: 13em}
	
	.form_table th,
	.form_table td			{border: 2px solid gray; padding: 8px; }
	
	.help_text			{font-size: x-small; color: gray}
	
	.form_table tr:nth-child(even)	{background: #BBBBBB}
	.form_table tr:nth-child(odd)	{background: #EEEEEE}
	
	.errorlist				{color: darkred}
{% endblock %}

{% block edit %}{% endblock %}

{% block heading %}
{% block title %}{% endblock %}
{% endblock %}

{% block main_content %}

	{%block afterform %}{% endblock %}
	<form action="." method="post">
			{% block form %}{% endblock %}
			<input style="margin-top: 5px" type="submit" name="submit" value="Submit">
	</form>
{% endblock %}

templates/base_list.html
{% extends "base.html" %}

{% block css %}
{{ block.super }}
	.filter_form		{background: #DDDDDD; padding:5px}
	.pagination			{margin: 5px; text-align: center; width: 100%; }
    .last_modified			{color: gray; margin-left: 10px}
{% endblock %}

{% block edit %}{% endblock %}

{% block heading %}
    {% block title %}{% endblock %}
{% endblock %}

{% block logo %}{% endblock %}

templates/base_view.html
{% extends "base.html" %}
{% load humanize %}

{% block javascript %}
<script type="text/javascript">

	$(document).ready(function() {

		$('#comment_form').submit( function() {
			if( $('#anon').is(':checked') ){
				$('#email').val('anonymous@example.com');
				$('#id_name').val("anonymous");
			}
		});

		$('#anon').click( function() {
			
			if( $('#anon').is(':checked') )
				$('#id_name').attr('disabled', 'disabled');
			else
				$('#id_name').attr('disabled', '');
		});
	});
</script>

{% endblock %}

{% block css %}
{{ block.super }}
/***********************************************************************/
/*                   base view                                         */
/***********************************************************************/

	#map_canvas						{width: 100%; height: 400px; background: green; margin-left: auto; margin-right: auto}

    .corner_link                    {display: block; float: left; text-align: left; width: 6em; margin-right: -6em;
                                     font-size: x-small; text-decoration: none; font-weight: normal; }

	
	.last_modified			{margin: 0px; padding-bottom: 2px; text-align: right; font-size: x-small !important; width: 100%; margin-top: 20px}

	.fancy_table					{border-collapse: collapse; margin-top: 0px; width: 100%; border: 2px solid black}
	.fancy_table thead td			{background: white; text-align: center; font-weight: bold; font-size: large}
	.fancy_table tr:nth-child(even)	{background: #EEEEEE}
	.fancy_table tr:nth-child(odd)	{background: #CCCCCC}
	.fancy_table td					{border: 1px solid #AAAAAA; padding: 5px; font-weight: normal; width: 50%; }
	.fancy_table td:first-child		{width: 12em}
	.fancy_table th					{border: 1px solid #AAAAAA; text-align: right; padding: 2px}
	
	.comment_div					{margin-bottom: 5px;}
	.comments_form_div				{margin-left: auto; margin-right: auto; width: 60%; }
	.comments_form_div textarea		{width: 100%; }
	.time_box						{color: #777777; margin-bottom: 10px; font-size: x-small}
	
	.single tr						{background: #CCCCCC !important}

	td.not_known					{height: 5em}
	ul								{margin: 0px; padding-left: 1.5em}
	
{% endblock %}

{% block heading %}
{% block title%}{% endblock %}
{% endblock %}

templates/edit_status.html
{% extends "base_form.html" %}

{% block title %}Editing the status of {{position}}{% endblock %}

{######################################################}

{% block css %}
<style type="text/css">
	.status_table td:first-child	{width: 15em;}
	.status_table td		{border: 1px solid black; width: 5em; text-align: center; padding: 2px}
	
	.status_table td:last-child	{background: lightred}
</style>
{% endblock %}

{######################################################}

{% block sub_heading %}
<a href="{{ position.get_absolute_url }}" class="view">View {{position}}</a><br />
<a href="/edit{{ position.get_absolute_url }}" class="edit">Edit {{position}}</a>
{% endblock %}

{######################################################}	
{% block form %}
<table>
	<tr>
		<th>{{form.reference.label_tag}}:</th>
		<td>{{form.reference}}</td>
		<td>{{form.errors}}</td>
	</tr>
</table>

<br />

<table summary="hiring status form" class="status_table">
	<tr>
		<td>Base</td>
		<td>Status Unknown</td>
		<td>Laying Off</td>
		<td>Not Hiring</td>
		{% if bases|length_is:"1" %}
		<td>Hiring</td>
		{% else %}
		<td>Hiring (Assign)</td>
		<td>Hiring (Choice)</td>
		{% endif %}
	</tr>

	{% for base in bases %}
	<tr>
		<td><strong><a href="{{ base.get_absolute_url }}" class="immutable">{{base}}</a></strong><br />{{ base.location_summary}}</td>
		
		<td><input type="radio" name="{{base.identifier}}" value="unknown" {{base.unknown_checked|safe}}/></td>
		<td><input type="radio" name="{{base.identifier}}" value="layoff" {{base.layoff_checked|safe}}/></td>
		<td><input type="radio" name="{{base.identifier}}" value="not" {{base.not_checked|safe}}/></td>
		{% if bases|length_is:"1" %}
		<td><input type="radio" name="{{base.identifier}}" value="choice" {{base.choice_checked|safe}}/></td>
		{% else %}
		<td><input type="radio" name="{{base.identifier}}" value="assign" {{base.assign_checked|safe}}/></td>
		<td><input type="radio" name="{{base.identifier}}" value="choice" {{base.choice_checked|safe}}/></td>
		{% endif %}
	</tr>
	{% endfor %}
</table>
{% endblock %}

templates/list_aircraft-company.html
{% extends "base_list.html" %}

{% block title %}{{type}}{% endblock %}

{% block sub_heading %}
	{% ifequal type "Aircraft" %}
		<a href="{% url new-aircraft %}" class="new">Create New Aircraft</a>
	{% else %}
		<a href="{% url new-company %}" class="new">Create New Company</a>
	{% endifequal %}
{% endblock %}

{% block main_content %}
	<div class="filter_form">
	<form action="." method="get">
		<table>
		{{searchform}}
		</table>
		
		<input type="submit">
	</form>
	</div>

	{% load pagination_tags %}
	{% autopaginate objects 50 %}
	<div class="pagnate">{% paginate %}</div>
	<ul>
	{% for object in objects %}
	<li><a class="{%ifequal type "Aircraft"%}immutable{%else%}view{%endifequal%}" href="{{ object.get_absolute_url }}">{{object}}</a></li>
	{% empty %}
		<li><strong>Nothing to show, sorry</strong></li>
	{% endfor %}
	</ul>
{% endblock %}

templates/list_aircraft.html
{% extends "base_list.html" %}

{% block title %}{{title}}Aircraft{% endblock %}

{% block css %}
{{ block.super }}
	.filter_form		{background: #DDDDDD; padding:5px}
{% endblock %}

{% block under_heading %}
<a href="/new/aircraft" class="new">Create New Aircraft</a>
{% endblock %}

{% block main_content %}
	<div class="filter_form">
	<form action="." method="get">
		<table>
		{{searchform}}
		</table>
		
		<input type="submit">
	</form>
	</div>
	
	<ul>
	{% for aircraft in aircrafts %}
		<li><a class="immutable" href="{{ aircraft.get_absolute_url }}">{{aircraft}}</li>
	{% empty %}
		<li><strong>Nothing to show, sorry</strong></li>
	{% endfor %}
	</ul>
{% endblock %}

templates/list_latest.html
{% extends "base_list.html" %}
{% load duration %}

{% block title %}Latest Changes{% endblock %}

{% block css %}
{{ block.super }}
	.last_modified			{color: gray;}
	.containers				{float: right; width: 50%; }
	.containers li			{margin-bottom: 10px}
{% endblock %}

{% block main_content %}
	<div class="containers">Latest Edited Positions:
	<ul>
	{% for position in positions %}
	<li>
		<a class="view" href="{{ position.get_absolute_url }}">{{position.company}} - {{ position }}</a><br>
		<span class="last_modified">{{ position.modified_seconds_ago|sectodur }} Ago</span>
	</li>
	{% endfor %}
	</ul>
	</div>

	<div class="containers">Latest Edited Companies:
		<ul>
		{% for company in companies %}
		<li>
			<a class="view" href="{{ company.get_absolute_url }}">{{ company }}</a><br>
			<span class="last_modified">{{ company.modified_seconds_ago|sectodur }} ago</span>
		</li>
		{% endfor %}
		</ul>
	</div>


{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}Sign In{% endblock %}

{% block body %}
<table>
	{form}}
</table>
{% endblock %}

templates/new-edit_aircraft.html
{% extends "base_form.html" %}

{% block title %}{% if form.instance.pk %}Edit{% else %}Add New{% endif %} Aircraft{% endblock %}

{% block sub_heading %}
	{% if form.instance.pk %}
	<a href="{{ form.instance.get_absolute_url }}" class="view">View {{form.instance}}</a>
	{% endif %}
{% endblock %}

{% block form%}
<table class="form_table">
	{% for field in form %}
	<tr>
		<th>{{field.label_tag}}:</th>
		
		<td>{{field}}
			<br><span class="help_text">{{field.help_text}}</span>
		</td>
	</tr>
	{% endfor %}
</table>
{% endblock %}

templates/new_route.html
{% extends "base.html" %}

{% block title %}New Route for {{opbase.base}}{% endblock %}

{% block css %}
	<style type="text/css">

		input[type="text"]		{width:4em}

	</style>
{% endblock %}

{% block javascript %}



{% endblock %}

{% block body %}
<div id="main_container">

	<h1>New Route for {{opbase.base}}</h1>
	<a href="/edit/operation/{{opbase.operation.pk}}" class="edit">Edit {{ opbase.operation }}</a>
	
	<hr class="top_divider" />
	
	<form action="." method="post">
		<div>
			{{opbase.base}} - {% for form in formset.forms %}{{form.base}}{{form.id}} - {{form.errors}}{% endfor %}{{opbase.base}}
			{{ formset.management_form }}
		</div>
		
		<hr />
		
		<table>
			{{routeform}}
		</table>
				
		<div>
			<input type="submit" value="Create New Route" />
		</div>
	</form>

</div>
{% endblock %}

templates/view_aircraft.html
{% extends "base_view.html" %}
{% load comments %}
{% load comments %}

{% block title %}{{aircraft}}{% endblock %}

{% block css %}
{{block.super }}
	.operations_box			{border: 1px solid black; background: lightgray; padding: 5px}
{% endblock %}

{% block edit_top %}"{{ aircraft.get_edit_url }}"{% endblock %}

{% block main_content %}

	<table class="fancy_table" summary="aircraft specs">
		<thead>
		<tr>
			<td colspan=2>General Information</td>
		</tr>
		</thead>
		
		<tr>
			<th>Type:</th>
			<td>{{aircraft.type}}</td>
		</tr>
		
		<tr>
			<th>Model:</th>
			<td>{{aircraft.model}}</td>
		</tr>
		
		<tr>
			<th>Manufacturer:</th>
			<td>{{aircraft.manufacturer}}</td>
		</tr>
		
		<tr>
			<th>Category/Class:</th>
			<td>{{aircraft.get_cat_class_display}}</td>
		</tr>
		
		<tr>
			<th>Engine Type:</th>
			<td>{{aircraft.get_engine_type_display}}</td>
		</tr>

		<tr>
			<th>Companies that use this aircraft:</th>
	
			<td>
				<ul>
				{% for company in companies %}
					<li><a class="view" href="{{ company.get_absolute_url }}">{{company}}</a></li>
				{% empty %}
					<span class="not_known">None</span>
				{% endfor %}
				</ul>
			</td>
		</tr>
	</table>
{##################################################}
{##################################################}
{#################comments#########################}
{##################################################}

{% get_comment_list for aircraft as comment_list %}
{% include "comments_table.html"%}
{% render_comment_form for aircraft %}

{% endblock %}

templates/view_airport.html
{% extends "base_view.html" %}

{% block title %}{{ airport.identifier }} - {{ airport.name }}{% endblock %}
{% block sub_heading %}{{airport.location_summary}}{% endblock %}

{% block edit %}&nbsp;{% endblock %}

{% block css %}
{{ block.super }}
	.airport_positions		{background: #DDDDDD; border: 1px solid black; padding: 1em; margin-bottom: 1em}
{% endblock %}

{% block javascript %}
	<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key={{ GOOGLE_MAPS_KEY }}" type="text/javascript"></script>
	<script type="text/javascript" src="{{ MEDIA_URL }}/javascripts/small_map.js"></script>
	
	<script type="text/javascript">

	var map;

	$(document).ready(function() {
		
		initialize();
		
		var kml = new GGeoXml('{{ SITE_URL }}{{ kmz_url }}', function(){
		
			if (kml.loadedCorrectly())
			{
				map.addOverlay(kml);
				kml.gotoDefaultViewport(map)
			}
			
			if (map.getZoom() > 6)
				map.setZoom(6)
		});
		
	});
	
	window.onunload = GUnload;
	</script>

{% endblock %}

{% block main_content %}
<div id="main_container">

	<div id="map_canvas" class="small_map"></div>

	<div class="airport_positions">
		<big>Companies with a base at this airport:</big>
		<br><br>

		{% for company in company_base %}
			<a href="{{ company.get_absolute_url }}" class="view">{{ company }}</a><br>
		{% empty %}
			<span class="not_known">None</span>
		{% endfor %}
	</div>

	<div class="airport_positions">
		<big>Operations that fly to this airport:</big>
		<br><br>

		{% for op in ops_fly %}
			<a href="{{ company.get_absolute_url }}" class="view">{{ op.company }} - {{ op.all_fleet }}</a><br>
		{% empty %}
			<span class="not_known">None</span>
		{% endfor %}
	</div>
</div>
{% endblock %}

templates/view_company.html
{% extends "base_view.html" %}
{% load comments %}

{% block edit_top %}"{{ company.get_edit_url }}"{% endblock %}
{% block title %}{{company.name}}{% endblock %}

{% block css %}
{{ block.super }}
	.optable		{background: white; border-collapse: collapse; max-width: 500px; margin-left: auto; margin-right: auto}
	.optable td		{width: 400px; background: white; border: 1px solid gray}
	.optable th		{border: 1px solid gray}
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="http://maps.google.com/maps?file=api&amp;v=2.x&amp;key={{ GOOGLE_MAPS_KEY }}"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}/javascripts/small_map.js"></script>

<script type="text/javascript">

	var map;

	$(document).ready(function() {
		
		var kml = new GGeoXml('{{ SITE_URL }}{{ kmz_url }}', function(){
		
			if (kml.loadedCorrectly())
			{
				map.addOverlay(kml);
				kml.gotoDefaultViewport(map)
			}
			
			if (map.getZoom() > 6)
				map.setZoom(6)
		});
		
		initialize();
	});
	
	window.onunload = GUnload;
</script>
{% endblock %}
	
{% block main_content %}
<table class="fancy_table" summary="Bases">

	<thead>
		<tr>
			<td colspan="2">Overview Map<a title="Download KML file for viewing in Google Earth" class="corner_link" href="{{ kmz_url }}">kml</a></td>
		</tr>
	</thead>
	
	<tr>
		<td>
			<div id="map_canvas"></div>
		</td>
	
	</tr>
</table>


<div class="last_modified">Last modified:  <strong>{{company.last_modified|date:"F d, Y"|default:"Never"}}</strong> {{company.last_modified|date:"(G:i.s T)"}}</div>	
<table class="fancy_table" summary="Position general information">
	<thead>
		<tr>
			<td colspan="2">Company Information</td>
		</tr>
	</thead>
	
	<tr>
		<th>Business Domain:</th>  <td>{{company.get_type_display|default:'<span class="not_known">Not Known</span>'}} </td>
	</tr>
	
	<tr>
		<th>Description:</th>  <td>{{ company.description|default:'<span class="not_known">Not Known</span>'}}</td>
	</tr>
	
	<tr>
		<th>Contact Info:</th>  <td>{{company.contact_info|default:'<span class="not_known">Not Known</span>'}}</td>
	</tr>
	
	<tr>
		<th>Website:</th>  <td>{% if company.website %}<a href="{{company.website}}" class="external">{{company.website}}</a> <img src="http://en.wikipedia.org/skins-1.5/monobook/external.png" />{% else %}<span class="not_known">Not Known</span>{% endif %} </td>
	</tr>
	
	<tr>
		<th>Call Sign:</th>  <td>{{company.call_sign|default:'<span class="not_known">Not Known</span>'}}</td>
	</tr>
	
	<tr>
		<th>Union:</th>  <td>{{company.union|default:'<span class="not_known">Not Known</span>'}}</td>
	</tr>
	
	<tr>
		<th>Jumpseat Privileges:</th>  <td>	{% ifequal company.jumpseat 0 %}
								<span class="not_known">Not Known</span>
							{% else %}
								{{ company.get_jumpseat_display }}
							{% endifequal %}
						</td>
	</tr>
	
		
	
	{#<tr>#}
	{#	<th>Number of people watching this company:</th>#}
	{#	<td>{{watchers|default:"0"}} {% if not already_watching %}<a class="watch" href="/watch/position/{{ company.pk }}">(Watch this company)</a>{%else%}<a href="/unwatch/position/{{ position.pk }}">(Unwatch this company)</a>{% endif %}</td>#}
	{#</tr>#}
</table>

<div class="last_modified">&nbsp;</div>	
<table class="fancy_table single" summary="Position general information">
	<thead>
		<tr>
			<td colspan="2">Operations</td>
		</tr>
	</thead>
	<tr>
	<td>	
	
	{#######################################}
	
	{% for operation in company.operation_set.all %}
		<div style="margin: 3px; padding: 10px;">
			<table class="optable">
				<tr>
					<th>Positions:</th>
					<td>
						<ul>
						{% for position in operation.positions.all %}
						<li><a href="{{ position.get_absolute_url }}" class="view">{{position}}</a></li>
						{% endfor %}
						</ul>
					</td>
				</tr>
				
				<tr>
					<th>Aircraft:</th>
					<td>
						<ul>
						{% for fleet in operation.fleet.all %}
						<li><a href="{{ fleet.aircraft.get_absolute_url }}" class="immutable">{{fleet}}</a></li>
						{% endfor %}
						</ul>
					</td>
				</tr>
				
				
				<tr>
					<th>Bases:</th>
					<td>
						<ul>
						{% for base in operation.bases.all %}
						<li><a href="{{ base.get_absolute_url }}" class="immutable">{{base}}</a></li>
						{% endfor %}
						</ul>
					</td>
				</tr>
			</table>
			
		</div>
	{% if not forloop.last %}<hr />{% endif %}
	{% empty %}
		<div style="text-align: center"><span class="not_known">None</span></div>
	{% endfor %}
	
	{#######################################}
	
	</td>
	</tr>
</table>

{% get_comment_list for company as comment_list %}
{% include "comments_table.html"%}
{% render_comment_form for company %}

{% endblock %}